name = "job-hunt"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "JOB_HUNT_DB"
database_name = "job-hunt-db"
database_id = "ff2452b6-e964-455c-9764-3d3d2869d22e"

[ai]
binding = "AI"
[vars]
SERPAPI_KEY = ""
GOOGLE_SEARCH_API_KEY = ""
GOOGLE_SEARCH_ENGINE_ID = ""
APP_PASSWORD = ""
